platform :ios do
  lane :beta do
    build_app(
      scheme: "App.xcscheme",
      workspace: "ios/App/App.xcworkspace",
      include_bitcode: true)
  end
end

lane :recreate_scheme do
  recreate_schemes(
    project: "./ios/App/App.xcodeproj"
  )
end
