name: build-ios-app
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: fastlane ios beta

      - uses: actions/checkout@v2
      - name: Result
        run: |
          xcodebuild -workspace ios/App/App.xcworkspace -list
          ls fastlane
          tree .
